<?php

namespace AppBundle\Repository;

/**
 * ClassroomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassroomRepository extends \Doctrine\ORM\EntityRepository
{
}
