<?php

namespace AppBundle\Repository;

/**
 * DanceCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DanceCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
