<?php

namespace AppBundle\Repository;

/**
 * DanceStyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DanceStyleRepository extends \Doctrine\ORM\EntityRepository
{
}
