<?php

namespace AppBundle\Repository;

/**
 * lessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lessonRepository extends \Doctrine\ORM\EntityRepository
{
}
