<?php

namespace AppBundle\Repository;

/**
 * OpinionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpinionRepository extends \Doctrine\ORM\EntityRepository
{
}
