<?php

namespace AppBundle\Repository;

/**
 * StyleCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StyleCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
