imports:
    - { resource: easy_admin_entities/danceStyle.yml }
    - { resource: easy_admin_entities/danceCategory.yml }
    - { resource: easy_admin_entities/event.yml }
    - { resource: easy_admin_entities/lesson.yml }
    - { resource: easy_admin_entities/level.yml }
    - { resource: easy_admin_entities/classroom.yml }

easy_admin:
    design:
        brand_color: '#8A0507'
        menu:
            - { entity: 'DanceStyle' }
            - { entity: 'danceCategory' }
            - { entity: 'Event' }
            - { entity: 'Lesson' }
            - { entity: 'Level' }
            - { entity: 'Classroom' }
            - { label: 'app.menu.backHome', route: 'homepage' } 
        assets:
            favicon: 'bundles/app/img/favicon.ico'
    site_name: 'Ami''danse'
    list:
        actions:
            - { name: 'edit', label: '', css_class: 'btn btn-warning', icon: 'edit' }
            - { name: 'delete', label: '', css_class: 'btn btn-danger', icon: 'trash' }
            