vich_uploader:
    db_driver: orm
    mappings:
        event_pictures:
            uri_prefix:         %app.path.event_pictures%
            upload_destination: %kernel.root_dir%/../web/uploads/pictures/events
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true



parameters:
    app.path.event_pictures: '/uploads/pictures/events'