easy_admin:
    translation_domain: 'messages'
    entities:
        DanceStyle:
            class: AppBundle\Entity\DanceStyle
            label: app.menu.danceStyle
            form: 
                fields:
                    - { property: 'name', type: 'text', label: 'admin.danceStyle.name', type_options: { required: true } }
                    - { property: 'description', type: 'textarea', label: 'admin.danceStyle.description', type_options: { required: false } }
                    - { property: 'danceCategories', label: 'admin.danceStyle.danceCategories' }
            new:
                title: 'admin.danceStyle.new'
            edit:
                title: 'admin.danceStyle.edit'